name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restor
    - name: Setup publish profile
      run: echo ${{ secrets.WEB_DEPLOY_PUBLISH_PROFILE }} >> publish.pubxml
    - name: Publish
      run: dotnet publish -p:PublishProfile=publish -p:Password=${{ secrets.WEB_DEPLOY_PASSWORD }} --configuration Release
