name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create publish profile folder
      run: mkdir Properties/PublishProfiles
    - name: Setup publish profile
      run: printf "${{ secrets.WEB_DEPLOY_PUBLISH_PROFILE }}" >> Properties/PublishProfiles/publish.pubxml
    - name: Test
      run: ls
    - name: Publish
      run: msbuild AngusBiniCals.csproj /p:PublishProfile=publish /p:Password=${{ secrets.WEB_DEPLOY_PASSWORD }}
